SUPABASE_URL = "https://qmyxfgtthdqvulfskoza.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFteXhmZ3R0aGRxdnVsZnNrb3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjI1MzksImV4cCI6MjA3NTQ5ODUzOX0.hgMQ0fuz2K-jgC1lwby5AI-16P35H5rx4PxsVpo0Cms"
